version: '3'

services:
  goatway:
    image: goatway
    ports:
      - "9090:9090"
    depends_on:
      - redis
  redis:
    image: redis:alpine
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf